name: generate

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: deepy/Pelican-Cid
          path: Pelican-Cid
      - name: GitHub Pages Pelican Build Action
        uses: nelsonjchen/gh-pages-pelican-action@0.2.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}    
          GH_PAGES_CNAME: cursed.build
          PELICAN_THEME_FOLDER: Pelican-Cid
